server {
    listen 80;

    location / {
        proxy_pass http://calendar-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-User alice;
        proxy_set_header X-Forwarded-Email alice@example.com;
        proxy_set_header X-Forwarded-Groups family,dev,ignored-group;
    }
}
