server {
    listen 80;

    location / {
        proxy_pass http://calendar-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-User carol;
        proxy_set_header X-Forwarded-Email carol@example.com;
        proxy_set_header X-Forwarded-Groups ignored-group;
    }
}
